import { useRouter } from "next/router";
import { createPortal } from "react-dom";
import { DarkModeContext } from "../context/DarkModeContext";
import { motion } from "framer-motion";
import HomeIcon from "@mui/icons-material/Home";
import BuildIcon from "@mui/icons-material/Build";
import PhotoLibraryIcon from "@mui/icons-material/PhotoLibrary";
import MiscellaneousServicesIcon from "@mui/icons-material/MiscellaneousServices";
import CommentIcon from "@mui/icons-material/Comment";
=======
import React, { useState, useContext, useRef, useEffect } from "react";
import { useRouter } from "next/router";
import { DarkModeContext } from "../context/DarkModeContext";
import MenuIcon from "@mui/icons-material/Menu";
import CloseIcon from "@mui/icons-material/Close";
import HomeIcon from "@mui/icons-material/Home";
import BuildIcon from "@mui/icons-material/Build";
import PhotoLibraryIcon from "@mui/icons-material/PhotoLibrary";
import MiscellaneousServicesIcon from "@mui/icons-material/MiscellaneousServices";
import CommentIcon from "@mui/icons-material/Comment";
